server:
  port: 8092
spring:
  application:
    name: eureka-client-provider
  zipkin:
    base-url: http://127.0.0.1:9411
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8091/eureka/

