zone.name: zone-1 # customer
server:
  port: 30005
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      # 标识本服务属于哪个zone    
      zone: zone-1
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    prefer-same-zone-eureka: true
    # 地区
    region: beijing
    availability-zones:
      # 注意zone顺序：本服务优先注册到zone1
      beijing: zone-1,zone-2
    service-url:
      zone-1: http://localhost:30001/eureka/
      zone-2: http://localhost:30002/eureka/